version: "2"
services:
    # sqldatabase1:
    #     container_name: sqldatabase1
    #     image: "microsoft/mssql-server-linux"
    #     environment:
    #         SA_PASSWORD: "Bl@bl@Move2018P*sword"
    #         ACCEPT_EULA: "Y"
    #         MSSQL_MEMORY_LIMIT_MB : "1024"

    #     depends_on:
    #         - mongo
    #mongodbar:
    #  container_name: mongodbar
    #  image: mongo:latest
    #  restart: always
    #  ports:
    #    - "27017:27017"
    #  logging:
    #    driver: none
    application:
       build: .
       restart: always
       ports:
          - "8080:8080"
       depends_on:
          - dbnouveau
       links:
          - dbnouveau
    dbnouveau:
        image: mysql
        #command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: 
          - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: mdp
            MYSQL_DATABASE: test
            MYSQL_USER: damien
            MYSQL_PASSWORD: mdp
    

