version: "2"
services:
    # sqldatabase1:
    #     container_name: sqldatabase1
    #     image: "microsoft/mssql-server-linux"
    #     environment:
    #         SA_PASSWORD: "Bl@bl@Move2018P*sword"
    #         ACCEPT_EULA: "Y"
    #         MSSQL_MEMORY_LIMIT_MB : "1024"
    #     depends_on:
    #         - mongo
    #mongodbar:
    #  container_name: mongodbar
    #  image: mongo:latest
    #  restart: always
    #  ports:
    #    - "27017:27017"
    #  logging:
    #    driver: none
    application:
       build: .
       restart: always
       ports:
          - "8080:8080"
       depends_on:
          - dbnouveau
       links:
          - dbnouveau
       networks :
            web_net :
                ipv4_address : 192.168.99.10
    dbnouveau:
        container_name: dbnouveau
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        #restart: always
        ports: 
          - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: blablamove_master
            MYSQL_USER: 176203_admin
            MYSQL_PASSWORD: admin
        volumes:
           - ./data/mysql:/var/lib/mysql
           - ./master.cnf:/etc/mysql/conf.d/master.cnf
           - ./MasterConfig:/docker-entrypoint-initdb.d
        networks :
            web_net :
                ipv4_address : 192.168.99.11
           
    dbnouveau2:
        container_name: dbnouveau2
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: 
          - "3307:3306"
        environment:
             MYSQL_ROOT_PASSWORD: admin
        #     MYSQL_DATABASE: blablamove_master
        #     MYSQL_USER: 176203_admin
        #     MYSQL_PASSWORD: admin
        volumes:
           - ./data2/mysql:/var/lib/mysql
           - ./slave.cnf:/etc/mysql/conf.d/slave.cnf
           - ./SlaveConfig:/docker-entrypoint-initdb.d
        networks :
            web_net :
                ipv4_address : 192.168.99.12
    myadm:
        image : phpmyadmin/phpmyadmin
        ports : 
           - "8085:80" 
        container_name: wpphpmyadmin
        links:
           - "dbnouveau:db"
        environment:
            MYSQL_USERNAME: 176203_admin
            MYSQL_ROOT_PASSWORD: admin
        restart: always
        networks :
            web_net :
                ipv4_address : 192.168.99.13
networks:
  web_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.99.0/25
        
