version: "2"
services:
    sqldatabase1:
        container_name: sqldatabase1
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "Bl@bl@Move2018P*sword"
            ACCEPT_EULA: "Y"
            MSSQL_MEMORY_LIMIT_MB : "1024"
    web:
        build: .
        restart: always
        ports:
           - "8080:8080"
        depends_on:
           - sqldatabase1
        links:
           - sqldatabase1
