package com.xaamruda.bbm.offers.model;

public enum OfferStatus {
	POSTED, AWAITING_CONFIRMATION, CONFIRMED, CLOSED , ABORTED, AWAITING_DEPOSIT_CONFIRMATION, DEPOSIT_DONE,
	AWAITING_RECEIPT_CONFIRMATION, RECEIPT_DONE
}
